dt-bindings: iio: add some missing variables
>>>
error: use of undeclared identifier 'PSY_IIO_CURRENT_QNOVO'
...
>>>

Signed-off-by: chickendrop89 <chickendrop89@gmail.com>